// <auto-generated />
using System;
using Govor.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Govor.Domain.Migrations
{
    [DbContext(typeof(GovorDbContext))]
    [Migration("20261003131521_PrimitiveGroupsAndRequiredChannel")]
    partial class PrimitiveGroupsAndRequiredChannel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Govor.Domain.Models.ChatGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsChannel")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReactionMode")
                        .HasColumnType("integer");

                    b.Property<long>("ReactionPolicyVersion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("ChatGroups");
                });

            modelBuilder.Entity("Govor.Domain.Models.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddresseeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeId");

                    b.HasIndex("RequesterId");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("Govor.Domain.Models.GroupAdmins", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique();

                    b.ToTable("GroupAdmins");
                });

            modelBuilder.Entity("Govor.Domain.Models.GroupInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("InvitationCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("integer");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserMakerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("InvitationCode")
                        .IsUnique();

                    b.HasIndex("UserMakerId");

                    b.ToTable("GroupInvitations");
                });

            modelBuilder.Entity("Govor.Domain.Models.GroupMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InvitationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("MemberSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InvitationId");

                    b.HasIndex("UserId");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique();

                    b.ToTable("GroupMemberships");
                });

            modelBuilder.Entity("Govor.Domain.Models.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("integer");

                    b.Property<int>("Participants")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("Govor.Domain.Models.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MineType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("Govor.Domain.Models.Messages.ChatPushNotification", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageId");

                    b.HasIndex("NextAttemptAt");

                    b.ToTable("ChatPushNotifications");
                });

            modelBuilder.Entity("Govor.Domain.Models.Messages.MediaAttachments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MediaFileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MediaFileId");

                    b.HasIndex("MessageId");

                    b.ToTable("MediaAttachments");
                });

            modelBuilder.Entity("Govor.Domain.Models.Messages.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChatGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PrivateChatId")
                        .HasColumnType("uuid");

                    b.Property<long>("ReactionsVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.Property<int>("RecipientType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ReplyToMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChatGroupId");

                    b.HasIndex("PrivateChatId");

                    b.HasIndex("RecipientId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Govor.Domain.Models.Messages.MessageReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReactedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReactionCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ReactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReactionId");

                    b.HasIndex("UserId");

                    b.HasIndex("MessageId", "UserId")
                        .IsUnique();

                    b.ToTable("MessageReactions");
                });

            modelBuilder.Entity("Govor.Domain.Models.Messages.MessageView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MessageId", "UserId")
                        .IsUnique();

                    b.ToTable("MessageViews");
                });

            modelBuilder.Entity("Govor.Domain.Models.PrivateChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserAId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserBId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PrivateChats");
                });

            modelBuilder.Entity("Govor.Domain.Models.Reactions.ChannelAllowedReaction", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReactionId")
                        .HasColumnType("uuid");

                    b.HasKey("GroupId", "ReactionId");

                    b.HasIndex("ReactionId");

                    b.ToTable("ChannelAllowedReactions");
                });

            modelBuilder.Entity("Govor.Domain.Models.Reactions.ReactionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMilliseconds")
                        .HasColumnType("integer");

                    b.Property<string>("Emoji")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MediaFileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PackId")
                        .HasColumnType("uuid");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("MediaFileId");

                    b.HasIndex("PackId");

                    b.ToTable("ReactionItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3000000-0000-0000-0001-000000000001"),
                            Code = "👍",
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationMilliseconds = 0,
                            Emoji = "👍",
                            Height = 0,
                            IsEnabled = true,
                            Kind = 0,
                            Name = "👍",
                            PackId = new Guid("b3000000-0000-0000-0000-000000000001"),
                            SizeBytes = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = new Guid("b3000000-0000-0000-0001-000000000002"),
                            Code = "👎",
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationMilliseconds = 0,
                            Emoji = "👎",
                            Height = 0,
                            IsEnabled = true,
                            Kind = 0,
                            Name = "👎",
                            PackId = new Guid("b3000000-0000-0000-0000-000000000001"),
                            SizeBytes = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = new Guid("b3000000-0000-0000-0001-000000000003"),
                            Code = "❤️",
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationMilliseconds = 0,
                            Emoji = "❤️",
                            Height = 0,
                            IsEnabled = true,
                            Kind = 0,
                            Name = "❤️",
                            PackId = new Guid("b3000000-0000-0000-0000-000000000001"),
                            SizeBytes = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = new Guid("b3000000-0000-0000-0001-000000000004"),
                            Code = "🔥",
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationMilliseconds = 0,
                            Emoji = "🔥",
                            Height = 0,
                            IsEnabled = true,
                            Kind = 0,
                            Name = "🔥",
                            PackId = new Guid("b3000000-0000-0000-0000-000000000001"),
                            SizeBytes = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = new Guid("b3000000-0000-0000-0001-000000000005"),
                            Code = "🥰",
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationMilliseconds = 0,
                            Emoji = "🥰",
                            Height = 0,
                            IsEnabled = true,
                            Kind = 0,
                            Name = "🥰",
                            PackId = new Guid("b3000000-0000-0000-0000-000000000001"),
                            SizeBytes = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = new Guid("b3000000-0000-0000-0001-000000000006"),
                            Code = "👏",
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationMilliseconds = 0,
                            Emoji = "👏",
                            Height = 0,
                            IsEnabled = true,
                            Kind = 0,
                            Name = "👏",
                            PackId = new Guid("b3000000-0000-0000-0000-000000000001"),
                            SizeBytes = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = new Guid("b3000000-0000-0000-0001-000000000007"),
                            Code = "😁",
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationMilliseconds = 0,
                            Emoji = "😁",
                            Height = 0,
                            IsEnabled = true,
                            Kind = 0,
                            Name = "😁",
                            PackId = new Guid("b3000000-0000-0000-0000-000000000001"),
                            SizeBytes = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = new Guid("b3000000-0000-0000-0001-000000000008"),
                            Code = "🤔",
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationMilliseconds = 0,
                            Emoji = "🤔",
                            Height = 0,
                            IsEnabled = true,
                            Kind = 0,
                            Name = "🤔",
                            PackId = new Guid("b3000000-0000-0000-0000-000000000001"),
                            SizeBytes = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = new Guid("b3000000-0000-0000-0001-000000000009"),
                            Code = "😢",
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationMilliseconds = 0,
                            Emoji = "😢",
                            Height = 0,
                            IsEnabled = true,
                            Kind = 0,
                            Name = "😢",
                            PackId = new Guid("b3000000-0000-0000-0000-000000000001"),
                            SizeBytes = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = new Guid("b3000000-0000-0000-0001-000000000010"),
                            Code = "🎉",
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationMilliseconds = 0,
                            Emoji = "🎉",
                            Height = 0,
                            IsEnabled = true,
                            Kind = 0,
                            Name = "🎉",
                            PackId = new Guid("b3000000-0000-0000-0000-000000000001"),
                            SizeBytes = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = new Guid("b3000000-0000-0000-0001-000000000011"),
                            Code = "🤯",
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationMilliseconds = 0,
                            Emoji = "🤯",
                            Height = 0,
                            IsEnabled = true,
                            Kind = 0,
                            Name = "🤯",
                            PackId = new Guid("b3000000-0000-0000-0000-000000000001"),
                            SizeBytes = 0,
                            Width = 0
                        },
                        new
                        {
                            Id = new Guid("b3000000-0000-0000-0001-000000000012"),
                            Code = "🙏",
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationMilliseconds = 0,
                            Emoji = "🙏",
                            Height = 0,
                            IsEnabled = true,
                            Kind = 0,
                            Name = "🙏",
                            PackId = new Guid("b3000000-0000-0000-0000-000000000001"),
                            SizeBytes = 0,
                            Width = 0
                        });
                });

            modelBuilder.Entity("Govor.Domain.Models.Reactions.ReactionPack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShareCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasFilter("\"IsDefault\" = TRUE");

                    b.HasIndex("ShareCode")
                        .IsUnique();

                    b.ToTable("ReactionPacks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default public emoji reactions",
                            IsDefault = true,
                            IsEnabled = true,
                            Name = "Emoji",
                            ShareCode = "default"
                        });
                });

            modelBuilder.Entity("Govor.Domain.Models.Reactions.UserReactionPack", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PackId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "PackId");

                    b.HasIndex("PackId");

                    b.ToTable("UserReactionPacks");
                });

            modelBuilder.Entity("Govor.Domain.Models.ServerCommunitySettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("AllowLeave")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RequiredChannelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequiredChannelId");

                    b.ToTable("ServerCommunitySettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowLeave = true
                        });
                });

            modelBuilder.Entity("Govor.Domain.Models.Users.Admin", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Govor.Domain.Models.Users.Crypto.OneTimePreKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserCryptoSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UploadedAt");

                    b.HasIndex("UserCryptoSessionId", "IsUsed");

                    b.ToTable("OneTimePreKeys");
                });

            modelBuilder.Entity("Govor.Domain.Models.Users.Crypto.SignedPreKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("PublicSignedPreKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("SignedPreKeySignature")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("UserCryptoSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserCryptoSessionId")
                        .IsUnique();

                    b.ToTable("SignedPreKeys");
                });

            modelBuilder.Entity("Govor.Domain.Models.Users.Crypto.UserCryptoSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("PublicIdentityKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("UserSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserSessionId")
                        .IsUnique();

                    b.ToTable("UserCryptoSessions");
                });

            modelBuilder.Entity("Govor.Domain.Models.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("IconId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InviteId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("WasOnline")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("InviteId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("WasOnline");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Govor.Domain.Models.Users.UserPushToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserSessionId")
                        .IsUnique();

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("UserPushTokens");
                });

            modelBuilder.Entity("Govor.Domain.Models.Users.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceInfo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("Govor.Domain.Models.ChatGroup", b =>
                {
                    b.HasOne("Govor.Domain.Models.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Govor.Domain.Models.Friendship", b =>
                {
                    b.HasOne("Govor.Domain.Models.Users.User", "Addressee")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Govor.Domain.Models.Users.User", "Requester")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Addressee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Govor.Domain.Models.GroupAdmins", b =>
                {
                    b.HasOne("Govor.Domain.Models.ChatGroup", null)
                        .WithMany("Admins")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Govor.Domain.Models.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Govor.Domain.Models.GroupInvitation", b =>
                {
                    b.HasOne("Govor.Domain.Models.ChatGroup", null)
                        .WithMany("InviteCodes")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Govor.Domain.Models.Users.User", "UserMaker")
                        .WithMany()
                        .HasForeignKey("UserMakerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserMaker");
                });

            modelBuilder.Entity("Govor.Domain.Models.GroupMembership", b =>
                {
                    b.HasOne("Govor.Domain.Models.ChatGroup", "ChatGroup")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Govor.Domain.Models.GroupInvitation", null)
                        .WithMany()
                        .HasForeignKey("InvitationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Govor.Domain.Models.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatGroup");
                });

            modelBuilder.Entity("Govor.Domain.Models.Messages.ChatPushNotification", b =>
                {
                    b.HasOne("Govor.Domain.Models.Messages.Message", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Govor.Domain.Models.Messages.MediaAttachments", b =>
                {
                    b.HasOne("Govor.Domain.Models.MediaFile", "MediaFile")
                        .WithMany()
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Govor.Domain.Models.Messages.Message", "Message")
                        .WithMany("MediaAttachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Govor.Domain.Models.Messages.Message", b =>
                {
                    b.HasOne("Govor.Domain.Models.ChatGroup", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatGroupId");

                    b.HasOne("Govor.Domain.Models.PrivateChat", null)
                        .WithMany("Messages")
                        .HasForeignKey("PrivateChatId");
                });

            modelBuilder.Entity("Govor.Domain.Models.Messages.MessageReaction", b =>
                {
                    b.HasOne("Govor.Domain.Models.Messages.Message", "Message")
                        .WithMany("Reactions")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Govor.Domain.Models.Reactions.ReactionItem", null)
                        .WithMany()
                        .HasForeignKey("ReactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Govor.Domain.Models.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Govor.Domain.Models.Messages.MessageView", b =>
                {
                    b.HasOne("Govor.Domain.Models.Messages.Message", null)
                        .WithMany("MessageViews")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Govor.Domain.Models.Reactions.ChannelAllowedReaction", b =>
                {
                    b.HasOne("Govor.Domain.Models.ChatGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Govor.Domain.Models.Reactions.ReactionItem", null)
                        .WithMany()
                        .HasForeignKey("ReactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Govor.Domain.Models.Reactions.ReactionItem", b =>
                {
                    b.HasOne("Govor.Domain.Models.MediaFile", null)
                        .WithMany()
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Govor.Domain.Models.Reactions.ReactionPack", "Pack")
                        .WithMany("Reactions")
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("Govor.Domain.Models.Reactions.ReactionPack", b =>
                {
                    b.HasOne("Govor.Domain.Models.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Govor.Domain.Models.Reactions.UserReactionPack", b =>
                {
                    b.HasOne("Govor.Domain.Models.Reactions.ReactionPack", null)
                        .WithMany()
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Govor.Domain.Models.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Govor.Domain.Models.ServerCommunitySettings", b =>
                {
                    b.HasOne("Govor.Domain.Models.ChatGroup", null)
                        .WithMany()
                        .HasForeignKey("RequiredChannelId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Govor.Domain.Models.Users.Admin", b =>
                {
                    b.HasOne("Govor.Domain.Models.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("Govor.Domain.Models.Users.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Govor.Domain.Models.Users.Crypto.OneTimePreKey", b =>
                {
                    b.HasOne("Govor.Domain.Models.Users.Crypto.UserCryptoSession", "UserCryptoSession")
                        .WithMany("OneTimePreKeys")
                        .HasForeignKey("UserCryptoSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserCryptoSession");
                });

            modelBuilder.Entity("Govor.Domain.Models.Users.Crypto.SignedPreKey", b =>
                {
                    b.HasOne("Govor.Domain.Models.Users.Crypto.UserCryptoSession", "UserCryptoSession")
                        .WithOne("SignedPreKey")
                        .HasForeignKey("Govor.Domain.Models.Users.Crypto.SignedPreKey", "UserCryptoSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserCryptoSession");
                });

            modelBuilder.Entity("Govor.Domain.Models.Users.Crypto.UserCryptoSession", b =>
                {
                    b.HasOne("Govor.Domain.Models.Users.UserSession", "UserSession")
                        .WithOne("CryptoSession")
                        .HasForeignKey("Govor.Domain.Models.Users.Crypto.UserCryptoSession", "UserSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSession");
                });

            modelBuilder.Entity("Govor.Domain.Models.Users.User", b =>
                {
                    b.HasOne("Govor.Domain.Models.Invitation", "Invite")
                        .WithMany("Users")
                        .HasForeignKey("InviteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invite");
                });

            modelBuilder.Entity("Govor.Domain.Models.Users.UserSession", b =>
                {
                    b.HasOne("Govor.Domain.Models.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Govor.Domain.Models.ChatGroup", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("InviteCodes");

                    b.Navigation("Members");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Govor.Domain.Models.Invitation", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Govor.Domain.Models.Messages.Message", b =>
                {
                    b.Navigation("MediaAttachments");

                    b.Navigation("MessageViews");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Govor.Domain.Models.PrivateChat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Govor.Domain.Models.Reactions.ReactionPack", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Govor.Domain.Models.Users.Crypto.UserCryptoSession", b =>
                {
                    b.Navigation("OneTimePreKeys");

                    b.Navigation("SignedPreKey")
                        .IsRequired();
                });

            modelBuilder.Entity("Govor.Domain.Models.Users.User", b =>
                {
                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("SentFriendRequests");
                });

            modelBuilder.Entity("Govor.Domain.Models.Users.UserSession", b =>
                {
                    b.Navigation("CryptoSession")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
